### ISSUE TITLE
Backend cleanup tracking issue

### ISSUE THREAD

**Issue by greenest-green** [JohnNarofsky/deiadventures#26]
The backend code has a number of problems I left in, in favor of completing an MVP in time for the talk at GenCon.

To make sure I address them after, I'm making this list. If I miss one, and don't fix it immediately, I'll edit this message to include it.

- [ ] The server does not yet actually enforce permissions. (#51)
- [ ] The endpoints we provide were provided ad-hoc as-needed to implement the MVP frontend. We should consider making them, and their access sites, more principled.
- [x] Error handling has a ton of repetition, because I didn't have time to focus on identifying patterns while unclear on the application requirements.
- [x] The way we currently do error propagation from transactions in many places is probably wrong. (We probably need to move some things into the `Err` variant so `ROLLBACK`s get issued.) 
- [ ] There are many many many SQL queries which access the same things, and it would be nice to unify them into the `db.rs` module so we avoid forgetting new requirements on an individual basis. (e.g., "we added a `deleted_date` column but forgot to filter out deleted quests in X query...")
- [ ] Generally, this thing needs to be refactored into smaller parts.
- [ ] Do a proper review of our Web security, to prevent cross site trickery in-browser.

In addition, there are many `TODO` comments about other things which will need to be addressed. This list is for broader problems.
