### ISSUE TITLE
Server Admin Tools Tracking Issue

### ISSUE THREAD

**Issue by green-narofsky** [JohnNarofsky/deiadventures#41]
Currently, these things are quite tedious:
- [ ] Setting up a demo database
- [ ] Adding the first admin to a new database
- [ ] Computing password hashes (you need this to make demo user data)

It would be nice to have a CLI tool which does these things.

(Priority: Medium. These are not user facing features, nor are they required for operation, but this is making onboarding more painful.)
